import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ blogPosts }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
      {blogPosts.map((blog, key) => {
                          return <div className="col-xl-6 mb-4" data-aos="fade-up" key={key}>
                              <div className="box p-sm-4 p-3">
                                 
                                     <h3 className='heading-box text-tertiary mb-2'>{blog.title}</h3>
                              
                              </div>
                          </div>
                      })}
      </main>
    </>
  );
}



 
// This gets called on every request
export async function getServerSideProps() {

  
  const { data } = await fetch(`https://api.lifecarevengad.com/graphql`, {
    method: "POST",
    headers: {
        "Content-Type": "application/json",
    },
    body: JSON.stringify({
        query: `
    query Posts {
        posts(first: 5) {
            nodes {
                databaseId
              title
               date
               slug
              featuredImage {
                node {
                  altText
                  sourceUrl
                }
              }
            }
          }
}
`,
    }),
    next: { revalidate: 10 },
}).then((res) => res.json());



let blogPosts = data.posts.nodes

//console.log(data.posts.nodes[0].title)


 
 
  return { props: { blogPosts } }
}